name: ✨ Feature Request
description: Suggest a new feature or enhancement for LightShowPi Neo
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "I considered X, but..."

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Audio Processing
        - GPIO/Hardware Control
        - LED/RGB Support
        - Configuration
        - Web Interface
        - Button Manager
        - Performance
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my use case)
        - High (would significantly improve experience)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: "I want to control my lights from..."
    validations:
      required: true

  - type: textarea
    id: mockup
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots, or links to examples
      placeholder: "Attach images or provide links"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, research, or references about the feature here

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed the following
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I have described the use case clearly
          required: true
